# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'Insurance',
            },
        ),
        migrations.CreateModel(
            name='Insurancetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('model', models.TextField()),
            ],
            options={
                'db_table': 'Insurancetype',
            },
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Insurancetype'),
        ),
    ]
